// Mocks generated by Mockito 5.4.6 from annotations
// in f_pod/test/features/music_player/music_player_view_model.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:f_pod/src/features/music_player/view_models/music_player_view_model.dart'
    as _i3;
import 'package:f_pod/src/features/music_player/models/music_player_model.dart'
    as _i2;
import 'package:flutter/cupertino.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMusicPlayerModel_0 extends _i1.SmartFake
    implements _i2.MusicPlayerModel {
  _FakeMusicPlayerModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MusicPlayerViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicPlayerViewModel extends _i1.Mock
    implements _i3.MusicPlayerViewModel {
  MockMusicPlayerViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MusicPlayerModel get musicPlayerModel =>
      (super.noSuchMethod(
            Invocation.getter(#musicPlayerModel),
            returnValue: _FakeMusicPlayerModel_0(
              this,
              Invocation.getter(#musicPlayerModel),
            ),
          )
          as _i2.MusicPlayerModel);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void initListener() => super.noSuchMethod(
    Invocation.method(#initListener, []),
    returnValueForMissingStub: null,
  );

  @override
  void nextAlbum() => super.noSuchMethod(
    Invocation.method(#nextAlbum, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousAlbum() => super.noSuchMethod(
    Invocation.method(#previousAlbum, []),
    returnValueForMissingStub: null,
  );

  @override
  void panHandler(_i4.DragUpdateDetails? details) => super.noSuchMethod(
    Invocation.method(#panHandler, [details]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
